services:
  db:
    image: postgis/postgis:17-3.5
    container_name: nyc-amenity-db
    environment:
      POSTGRES_DB: nyc_amenity
      POSTGRES_USER: amenity_user
      POSTGRES_PASSWORD: amenity_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: